import { config } from './config.js';
import { logger } from './logger.js';
import { Router } from './router.js';
import { modelResolver } from './models.js';
import { ANTIGRAVITY_CONTEXT } from './antigravity-context.js';
import { registerBuiltinPlugins } from './plugins/builtin-plugins.js';
import { toolCapabilityRegistry } from './tool-capabilities.js';
import { normalizeToolCall } from './tool-normalizer.js';
import type { MappedRequest } from './mapper.js';
import type { OpenAIMessage } from './mapper.js';

// Ensure built-in plugins are registered at module load time
registerBuiltinPlugins();

export function extractConvId(requestId: string): string {
  const parts = requestId?.split('/') || [];
  return parts.length >= 2 ? parts.slice(0, 2).join('/') : requestId;
}

export const reasoningStore = new Map<string, string[]>();

export function saveReasoning(convId: string, thoughtText: string): void {
  if (!reasoningStore.has(convId)) reasoningStore.set(convId, []);
  reasoningStore.get(convId)!.push(thoughtText);
}

export function injectReasoning(messages: OpenAIMessage[], convId: string): void {
  const rcs = reasoningStore.get(convId);
  if (!rcs) {
    // Ensure all assistant messages have reasoning_content even when no store
    for (const msg of messages) {
      if (msg.role === 'assistant' && !msg.reasoning_content) {
        const c = msg.content;
        msg.reasoning_content = typeof c === 'string' ? c : ' ';
      }
    }
    return;
  }
  // Collect assistant message indices in chronological order
  const asstIdxs: number[] = [];
  for (let i = 0; i < messages.length; i++) {
    if (messages[i].role === 'assistant') asstIdxs.push(i);
  }
  // Inject store entries into the LAST N assistant messages
  // The reasoning store grows in response order (oldest first).
  // Assistant messages in the request are also chronological.
  // Each response adds one assistant message, so store[N] corresponds
  // to the (asstCount - storeLen + N)-th assistant message from the end.
  const injectCount = Math.min(rcs.length, asstIdxs.length);
  const msgOffset = asstIdxs.length - injectCount;
  const storeOffset = rcs.length - injectCount;
  for (let i = 0; i < injectCount; i++) {
    const msg = messages[asstIdxs[msgOffset + i]];
    msg.reasoning_content = rcs[storeOffset + i];
  }
  // Old assistant messages (before this session) need a fallback
  for (let i = 0; i < msgOffset; i++) {
    const msg = messages[asstIdxs[i]];
    if (!msg.reasoning_content) {
      const c = msg.content;
      msg.reasoning_content = typeof c === 'string' ? c : ' ';
    }
  }
}

let router: Router;

function getRouter(): Router {
  if (!router) {
    router = new Router(config.providers, modelResolver, { retries: config.retries, backoffMs: config.backoffMs });
  }
  return router;
}

export function reloadRouter(): void {
  config.reload();
  if (router) {
    router.updateProviders(config.providers, { retries: config.retries, backoffMs: config.backoffMs });
  }
  modelResolver.reload();
  logger.info('[engine] Router, config, and model maps reloaded');
}

/**
 * Normalize a tool call from an external LLM.
 * Uses the ToolNormalizer to fix names, params, types, and defaults.
 * Falls back to simple internal-param stripping if normalizer doesn't apply.
 */
const ANTIGRAVITY_INTERNAL_ONLY = new Set([
  'toolAction', 'toolSummary', 'ToolAction', 'ToolSummary',
]);

function normalizeToolArgs(args: Record<string, unknown>, toolName: string): Record<string, unknown> {
  // First: strip Antigravity internal params (these are injected by the runtime)
  const cleaned: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(args)) {
    if (!ANTIGRAVITY_INTERNAL_ONLY.has(key)) cleaned[key] = value;
  }
  if (Object.keys(cleaned).length === 0) return args;

  // Second: run through the tool normalizer for schema-aware fixes
  const result = normalizeToolCall(toolName, cleaned);
  if (result.warnings) {
    logger.info(`[normalizer] ${result.warnings.join('; ')}`);
  }
  return result.args;
}

/**
 * Ensures that for every tool call generated by an assistant message,
 * there is a matching tool response message with the same tool_call_id,
 * and vice-versa (removes orphaned tool responses).
 * This prevents strict backends like DeepSeek/OpenAI from throwing 400 Bad Request
 * when there's an mismatch (e.g. from cancelled or failed tool calls).
 */
export function alignToolCallsAndResponses(messages: OpenAIMessage[]): OpenAIMessage[] {
  // 1. Group all tool messages by tool_call_id
  const toolMessagesMap = new Map<string, OpenAIMessage[]>();
  for (const m of messages) {
    if (m.role === 'tool' && m.tool_call_id) {
      if (!toolMessagesMap.has(m.tool_call_id)) {
        toolMessagesMap.set(m.tool_call_id, []);
      }
      toolMessagesMap.get(m.tool_call_id)!.push(m);
    }
  }

  const cleanedMessages: OpenAIMessage[] = [];
  const usedToolMessages = new Set<OpenAIMessage>();

  for (const m of messages) {
    if (m.role === 'assistant' && m.tool_calls && Array.isArray(m.tool_calls) && m.tool_calls.length > 0) {
      const cloned = { ...m };
      const originalLen = cloned.tool_calls.length;
      
      // Filter tool calls to only keep those that have a corresponding response
      cloned.tool_calls = cloned.tool_calls.filter(tc => tc.id && toolMessagesMap.has(tc.id));
      
      if (cloned.tool_calls.length === 0) {
        delete cloned.tool_calls;
        if (cloned.content === null || cloned.content === undefined) {
          cloned.content = '';
        }
        cleanedMessages.push(cloned);
      } else {
        if (cloned.tool_calls.length < originalLen) {
          logger.warn(`[engine] Filtered out ${originalLen - cloned.tool_calls.length} unresponded tool calls from assistant message`);
        }
        
        // Push the assistant message
        cleanedMessages.push(cloned);
        
        // Immediately push the corresponding tool response messages, preserving relative order of tool calls
        for (const tc of cloned.tool_calls) {
          const list = toolMessagesMap.get(tc.id);
          if (list) {
            for (const toolMsg of list) {
              cleanedMessages.push(toolMsg);
              usedToolMessages.add(toolMsg);
            }
          }
        }
      }
    } else if (m.role === 'tool') {
      // If we encounter a tool message in the main flow, we only push it if it has NOT been used.
      // If it hasn't been used, it means it's an orphaned tool response (discarded) or we missed it.
      // So we skip it.
      if (usedToolMessages.has(m)) {
        continue;
      }
      logger.warn(`[engine] Discarding orphaned or out-of-order tool response for id: ${m.tool_call_id}`);
    } else {
      // Push all other messages (user, system)
      cleanedMessages.push(m);
    }
  }

  return cleanedMessages;
}

export type StreamResponseChunk =
  | { type: 'text'; content: string; provider?: string; resolvedModel?: string; sessionId?: string }
  | { type: 'thought'; content: string; provider?: string; resolvedModel?: string; sessionId?: string }
  | { type: 'tool-call'; name: string; args: Record<string, unknown>; provider?: string; resolvedModel?: string }
  | { type: 'attempt'; provider: string; resolvedModel: string; attempt: number; status: string; fallback?: boolean };

export async function* streamResponse(
  mapped: MappedRequest,
  modelId?: string,
  abortSignal?: AbortSignal,
): AsyncGenerator<StreamResponseChunk> {
  const model = modelId || 'default';
  const r = getRouter();
  const providerIds = config.providerPriority;

  logger.info(`Intercept: ${model}`, {
    messageCount: mapped.messages.length,
    hasTools: !!mapped.tools && Object.keys(mapped.tools).length > 0,
    hasSystem: !!mapped.system,
  });

  try {
    // Sync per-request tools into the capability registry for normalization
    toolCapabilityRegistry.setDynamicTools(mapped.tools);

    // Phase 2: Inject Antigravity runtime identity if this is the Antigravity agent.
    // We check if run_command is in the tools schema to avoid injecting this for normal chat.
    const isAgent = mapped.tools && ('run_command' in mapped.tools);
    const shouldInject = ANTIGRAVITY_CONTEXT.enabled && isAgent && !mapped.skipAgentContext;

    if (shouldInject) {
      const ctx = ANTIGRAVITY_CONTEXT.prompt;
      const existing = mapped.system;
      mapped.system = existing ? `${ctx}\n\n${existing}` : ctx;
    }

    // CRITICAL FIX: Inject mapped.system as a real system-role message so it
    // reaches the model. Prior to this fix, mapped.system was set but never
    // included in the messages array sent to the router/adapter — the model
    // never saw its working directory, tool rules, or antigravity context.
    if (mapped.system) {
      // Only prepend if there isn't already a system message (avoid duplicates)
      if (!mapped.messages.some(msg => msg.role === 'system')) {
        mapped.messages.unshift({
          role: 'system' as const,
          content: mapped.system,
        });
      }
    }

    // Also inject a prompt telling the model to read agent-context.md for
    // the full operating manual. Include explicit file path.
    if (shouldInject && !mapped.messages.some(msg => msg.role === 'user' && typeof msg.content === 'string' &&
      msg.content.includes('Read the agent-context.md file using the view_file tool')
    )) {
      const contextPath = process.env.AGENT_CONTEXT_PATH || 'agent-context.md';
      mapped.messages.unshift({
        role: 'user' as const,
        content: `Read the agent-context.md file using the view_file tool to adopt the runtime identity. Use this tool to access the complete operating manual for external agents before proceeding with your task. The file is located at: ${contextPath}. This includes the critical tool selection rules, subagent doctrine, verification requirements, and confidence framework needed to use Antigravity correctly. You must read this file to understand when and how to use all available tools, including manage_task for background process management and when to spawn agents for parallel execution.`
      });
    }

    const alignedMessages = alignToolCallsAndResponses(mapped.messages);
    const gen = r.execute(providerIds, model, alignedMessages, mapped.tools as any, {
      maxTokens: mapped.maxTokens,
      temperature: mapped.temperature,
      topP: mapped.topP,
      stopSequences: mapped.stopSequences,
      providerOptions: mapped.providerOptions,
    }, abortSignal, mapped.system);

    for await (const chunk of gen) {
      const prov = (chunk as any).provider;
      const rmodel = (chunk as any).resolvedModel;
      const sid = (chunk as any).sessionId as string | undefined;
      if (chunk.type === 'text') {
        yield { type: 'text', content: chunk.content || '', provider: prov, resolvedModel: rmodel, sessionId: sid };
      } else if (chunk.type === 'thought') {
        yield { type: 'thought', content: chunk.content || '', provider: prov, resolvedModel: rmodel, sessionId: sid };
      } else if (chunk.type === 'tool-call') {
        const toolName = chunk.name || 'unknown';
        yield { type: 'tool-call', name: toolName, args: normalizeToolArgs(chunk.args || {}, toolName), provider: prov, resolvedModel: rmodel };
      } else if (chunk.type === 'attempt') {
        // A4: surface router's attempt events to the dashboard so failover
        // telemetry is visible. The downstream consumer in index.ts already
        // handles 'attempt' chunks — it was just never receiving them.
        yield {
          type: 'attempt',
          provider: prov || '',
          resolvedModel: rmodel || '',
          attempt: (chunk as any).attempt ?? 1,
          status: (chunk as any).status || 'trying',
          fallback: (chunk as any).fallback,
        };
      } else if (chunk.type === 'error') {
        throw new Error(chunk.content || 'router error');
      }
    }
  } catch (err: any) {
    logger.error(`[engine] stream error`, { error: err.message });
    throw err;
  }
}

export async function generateResponse(
  mapped: MappedRequest,
  modelId?: string,
): Promise<{ text: string; finishReason: string | null }> {
  const model = modelId || 'default';
  const r = getRouter();
  const providerIds = config.providerPriority;

  try {
    // Phase 2: Inject Antigravity runtime identity if this is the Antigravity agent.
    // We check if run_command is in the tools schema to avoid injecting this for normal chat.
    const isAgent = mapped.tools && ('run_command' in mapped.tools);
    const shouldInject = ANTIGRAVITY_CONTEXT.enabled && isAgent && !mapped.skipAgentContext;

    if (shouldInject) {
      const ctx = ANTIGRAVITY_CONTEXT.prompt;
      const existing = mapped.system;
      mapped.system = existing ? `${ctx}\n\n${existing}` : ctx;
    }

    // CRITICAL FIX: Inject mapped.system as a real system-role message so it
    // reaches the model (same fix as streamResponse above).
    if (mapped.system) {
      if (!mapped.messages.some(msg => msg.role === 'system')) {
        mapped.messages.unshift({
          role: 'system' as const,
          content: mapped.system,
        });
      }
    }

    // Also inject a prompt telling the model to read agent-context.md for
    // the full operating manual. Include explicit file path.
    if (shouldInject && !mapped.messages.some(msg => msg.role === 'user' && typeof msg.content === 'string' &&
      msg.content.includes('Read the agent-context.md file using the view_file tool')
    )) {
      const contextPath = process.env.AGENT_CONTEXT_PATH || 'agent-context.md';
      mapped.messages.unshift({
        role: 'user' as const,
        content: `Read the agent-context.md file using the view_file tool to adopt the runtime identity. Use this tool to access the complete operating manual for external agents before proceeding with your task. The file is located at: ${contextPath}. This includes the critical tool selection rules, subagent doctrine, verification requirements, and confidence framework needed to use Antigravity correctly. You must read this file to understand when and how to use all available tools, including manage_task for background process management and when to spawn agents for parallel execution.`
      });
    }

    const alignedMessages = alignToolCallsAndResponses(mapped.messages);
    const gen = r.execute(providerIds, model, alignedMessages, mapped.tools as any, {
      maxTokens: mapped.maxTokens,
      temperature: mapped.temperature,
      topP: mapped.topP,
      stopSequences: mapped.stopSequences,
      providerOptions: mapped.providerOptions,
    }, undefined, mapped.system);

    let text = '';
    for await (const chunk of gen) {
      if (chunk.type === 'text') text += chunk.content || '';
      if (chunk.type === 'error') throw new Error(chunk.content);
    }
    return { text, finishReason: 'STOP' };
  } catch (err: any) {
    logger.error(`[engine] generate error`, { error: err.message });
    return { text: `Error: ${err.message}`, finishReason: 'ERROR' };
  }
}
